// Code generated by go-swagger; DO NOT EDIT.

package outgoing_webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/bitrise-io/bitrise-api-client/models"
)

// OutgoingWebhookDeleteReader is a Reader for the OutgoingWebhookDelete structure.
type OutgoingWebhookDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OutgoingWebhookDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOutgoingWebhookDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewOutgoingWebhookDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewOutgoingWebhookDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewOutgoingWebhookDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewOutgoingWebhookDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOutgoingWebhookDeleteOK creates a OutgoingWebhookDeleteOK with default headers values
func NewOutgoingWebhookDeleteOK() *OutgoingWebhookDeleteOK {
	return &OutgoingWebhookDeleteOK{}
}

/*OutgoingWebhookDeleteOK handles this case with default header values.

OK
*/
type OutgoingWebhookDeleteOK struct {
	Payload *models.V0AppWebhookDeletedResponseModel
}

func (o *OutgoingWebhookDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookDeleteOK  %+v", 200, o.Payload)
}

func (o *OutgoingWebhookDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V0AppWebhookDeletedResponseModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOutgoingWebhookDeleteBadRequest creates a OutgoingWebhookDeleteBadRequest with default headers values
func NewOutgoingWebhookDeleteBadRequest() *OutgoingWebhookDeleteBadRequest {
	return &OutgoingWebhookDeleteBadRequest{}
}

/*OutgoingWebhookDeleteBadRequest handles this case with default header values.

Bad Request
*/
type OutgoingWebhookDeleteBadRequest struct {
	Payload *models.ServiceStandardErrorRespModel
}

func (o *OutgoingWebhookDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *OutgoingWebhookDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOutgoingWebhookDeleteUnauthorized creates a OutgoingWebhookDeleteUnauthorized with default headers values
func NewOutgoingWebhookDeleteUnauthorized() *OutgoingWebhookDeleteUnauthorized {
	return &OutgoingWebhookDeleteUnauthorized{}
}

/*OutgoingWebhookDeleteUnauthorized handles this case with default header values.

Unauthorized
*/
type OutgoingWebhookDeleteUnauthorized struct {
	Payload *models.ServiceStandardErrorRespModel
}

func (o *OutgoingWebhookDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookDeleteUnauthorized  %+v", 401, o.Payload)
}

func (o *OutgoingWebhookDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOutgoingWebhookDeleteNotFound creates a OutgoingWebhookDeleteNotFound with default headers values
func NewOutgoingWebhookDeleteNotFound() *OutgoingWebhookDeleteNotFound {
	return &OutgoingWebhookDeleteNotFound{}
}

/*OutgoingWebhookDeleteNotFound handles this case with default header values.

Not Found
*/
type OutgoingWebhookDeleteNotFound struct {
	Payload *models.ServiceStandardErrorRespModel
}

func (o *OutgoingWebhookDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookDeleteNotFound  %+v", 404, o.Payload)
}

func (o *OutgoingWebhookDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOutgoingWebhookDeleteInternalServerError creates a OutgoingWebhookDeleteInternalServerError with default headers values
func NewOutgoingWebhookDeleteInternalServerError() *OutgoingWebhookDeleteInternalServerError {
	return &OutgoingWebhookDeleteInternalServerError{}
}

/*OutgoingWebhookDeleteInternalServerError handles this case with default header values.

Internal Server Error
*/
type OutgoingWebhookDeleteInternalServerError struct {
	Payload *models.ServiceStandardErrorRespModel
}

func (o *OutgoingWebhookDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookDeleteInternalServerError  %+v", 500, o.Payload)
}

func (o *OutgoingWebhookDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
