// Code generated by go-swagger; DO NOT EDIT.

package android_keystore_file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new android keystore file API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for android keystore file API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AndroidKeystoreFileCreate creates an android keystore file

Add a new Android keystore file to an app
*/
func (a *Client) AndroidKeystoreFileCreate(params *AndroidKeystoreFileCreateParams, authInfo runtime.ClientAuthInfoWriter) (*AndroidKeystoreFileCreateCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAndroidKeystoreFileCreateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "android-keystore-file-create",
		Method:             "POST",
		PathPattern:        "/apps/{app-slug}/android-keystore-files",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AndroidKeystoreFileCreateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AndroidKeystoreFileCreateCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for android-keystore-file-create: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
AndroidKeystoreFileList gets a list of the android keystore files

List all the android keystore files that have been uploaded to a specific app.
*/
func (a *Client) AndroidKeystoreFileList(params *AndroidKeystoreFileListParams, authInfo runtime.ClientAuthInfoWriter) (*AndroidKeystoreFileListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAndroidKeystoreFileListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "android-keystore-file-list",
		Method:             "GET",
		PathPattern:        "/apps/{app-slug}/android-keystore-files",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AndroidKeystoreFileListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AndroidKeystoreFileListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for android-keystore-file-list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
