// Code generated by go-swagger; DO NOT EDIT.

package build_artifact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewArtifactShowParams creates a new ArtifactShowParams object
// with the default values initialized.
func NewArtifactShowParams() *ArtifactShowParams {
	var ()
	return &ArtifactShowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewArtifactShowParamsWithTimeout creates a new ArtifactShowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewArtifactShowParamsWithTimeout(timeout time.Duration) *ArtifactShowParams {
	var ()
	return &ArtifactShowParams{

		timeout: timeout,
	}
}

// NewArtifactShowParamsWithContext creates a new ArtifactShowParams object
// with the default values initialized, and the ability to set a context for a request
func NewArtifactShowParamsWithContext(ctx context.Context) *ArtifactShowParams {
	var ()
	return &ArtifactShowParams{

		Context: ctx,
	}
}

// NewArtifactShowParamsWithHTTPClient creates a new ArtifactShowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewArtifactShowParamsWithHTTPClient(client *http.Client) *ArtifactShowParams {
	var ()
	return &ArtifactShowParams{
		HTTPClient: client,
	}
}

/*ArtifactShowParams contains all the parameters to send to the API endpoint
for the artifact show operation typically these are written to a http.Request
*/
type ArtifactShowParams struct {

	/*AppSlug
	  App slug

	*/
	AppSlug string
	/*ArtifactSlug
	  Artifact slug

	*/
	ArtifactSlug string
	/*BuildSlug
	  Build slug

	*/
	BuildSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the artifact show params
func (o *ArtifactShowParams) WithTimeout(timeout time.Duration) *ArtifactShowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the artifact show params
func (o *ArtifactShowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the artifact show params
func (o *ArtifactShowParams) WithContext(ctx context.Context) *ArtifactShowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the artifact show params
func (o *ArtifactShowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the artifact show params
func (o *ArtifactShowParams) WithHTTPClient(client *http.Client) *ArtifactShowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the artifact show params
func (o *ArtifactShowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppSlug adds the appSlug to the artifact show params
func (o *ArtifactShowParams) WithAppSlug(appSlug string) *ArtifactShowParams {
	o.SetAppSlug(appSlug)
	return o
}

// SetAppSlug adds the appSlug to the artifact show params
func (o *ArtifactShowParams) SetAppSlug(appSlug string) {
	o.AppSlug = appSlug
}

// WithArtifactSlug adds the artifactSlug to the artifact show params
func (o *ArtifactShowParams) WithArtifactSlug(artifactSlug string) *ArtifactShowParams {
	o.SetArtifactSlug(artifactSlug)
	return o
}

// SetArtifactSlug adds the artifactSlug to the artifact show params
func (o *ArtifactShowParams) SetArtifactSlug(artifactSlug string) {
	o.ArtifactSlug = artifactSlug
}

// WithBuildSlug adds the buildSlug to the artifact show params
func (o *ArtifactShowParams) WithBuildSlug(buildSlug string) *ArtifactShowParams {
	o.SetBuildSlug(buildSlug)
	return o
}

// SetBuildSlug adds the buildSlug to the artifact show params
func (o *ArtifactShowParams) SetBuildSlug(buildSlug string) {
	o.BuildSlug = buildSlug
}

// WriteToRequest writes these params to a swagger request
func (o *ArtifactShowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app-slug
	if err := r.SetPathParam("app-slug", o.AppSlug); err != nil {
		return err
	}

	// path param artifact-slug
	if err := r.SetPathParam("artifact-slug", o.ArtifactSlug); err != nil {
		return err
	}

	// path param build-slug
	if err := r.SetPathParam("build-slug", o.BuildSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
