// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgListParams creates a new OrgListParams object
// with the default values initialized.
func NewOrgListParams() *OrgListParams {

	return &OrgListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgListParamsWithTimeout creates a new OrgListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgListParamsWithTimeout(timeout time.Duration) *OrgListParams {

	return &OrgListParams{

		timeout: timeout,
	}
}

// NewOrgListParamsWithContext creates a new OrgListParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrgListParamsWithContext(ctx context.Context) *OrgListParams {

	return &OrgListParams{

		Context: ctx,
	}
}

// NewOrgListParamsWithHTTPClient creates a new OrgListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrgListParamsWithHTTPClient(client *http.Client) *OrgListParams {

	return &OrgListParams{
		HTTPClient: client,
	}
}

/*OrgListParams contains all the parameters to send to the API endpoint
for the org list operation typically these are written to a http.Request
*/
type OrgListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the org list params
func (o *OrgListParams) WithTimeout(timeout time.Duration) *OrgListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the org list params
func (o *OrgListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the org list params
func (o *OrgListParams) WithContext(ctx context.Context) *OrgListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the org list params
func (o *OrgListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the org list params
func (o *OrgListParams) WithHTTPClient(client *http.Client) *OrgListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the org list params
func (o *OrgListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OrgListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
