// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgShowParams creates a new OrgShowParams object
// with the default values initialized.
func NewOrgShowParams() *OrgShowParams {
	var ()
	return &OrgShowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgShowParamsWithTimeout creates a new OrgShowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgShowParamsWithTimeout(timeout time.Duration) *OrgShowParams {
	var ()
	return &OrgShowParams{

		timeout: timeout,
	}
}

// NewOrgShowParamsWithContext creates a new OrgShowParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrgShowParamsWithContext(ctx context.Context) *OrgShowParams {
	var ()
	return &OrgShowParams{

		Context: ctx,
	}
}

// NewOrgShowParamsWithHTTPClient creates a new OrgShowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrgShowParamsWithHTTPClient(client *http.Client) *OrgShowParams {
	var ()
	return &OrgShowParams{
		HTTPClient: client,
	}
}

/*OrgShowParams contains all the parameters to send to the API endpoint
for the org show operation typically these are written to a http.Request
*/
type OrgShowParams struct {

	/*OrgSlug
	  The organization slug

	*/
	OrgSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the org show params
func (o *OrgShowParams) WithTimeout(timeout time.Duration) *OrgShowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the org show params
func (o *OrgShowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the org show params
func (o *OrgShowParams) WithContext(ctx context.Context) *OrgShowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the org show params
func (o *OrgShowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the org show params
func (o *OrgShowParams) WithHTTPClient(client *http.Client) *OrgShowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the org show params
func (o *OrgShowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgSlug adds the orgSlug to the org show params
func (o *OrgShowParams) WithOrgSlug(orgSlug string) *OrgShowParams {
	o.SetOrgSlug(orgSlug)
	return o
}

// SetOrgSlug adds the orgSlug to the org show params
func (o *OrgShowParams) SetOrgSlug(orgSlug string) {
	o.OrgSlug = orgSlug
}

// WriteToRequest writes these params to a swagger request
func (o *OrgShowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param org-slug
	if err := r.SetPathParam("org-slug", o.OrgSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
