// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new organizations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for organizations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
OrgList lists the organizations that the user is part of

List all Bitrise organizations that the user is part of
*/
func (a *Client) OrgList(params *OrgListParams, authInfo runtime.ClientAuthInfoWriter) (*OrgListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrgListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "org-list",
		Method:             "GET",
		PathPattern:        "/organizations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OrgListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*OrgListOK), nil

}

/*
OrgShow gets a specified organization

Get a specified Bitrise organization that the user is part of.
*/
func (a *Client) OrgShow(params *OrgShowParams, authInfo runtime.ClientAuthInfoWriter) (*OrgShowOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrgShowParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "org-show",
		Method:             "GET",
		PathPattern:        "/organizations/{org-slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OrgShowReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*OrgShowOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
