// Code generated by go-swagger; DO NOT EDIT.

package apple_api_credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new apple api credentials API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for apple api credentials API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AppleAPICredentialList lists apple API credentials for a specific user

List Apple API credentials for a specific Bitrise user
*/
func (a *Client) AppleAPICredentialList(params *AppleAPICredentialListParams, authInfo runtime.ClientAuthInfoWriter) (*AppleAPICredentialListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAppleAPICredentialListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "apple-api-credential-list",
		Method:             "GET",
		PathPattern:        "/users/{user-slug}/apple-api-credentials",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AppleAPICredentialListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AppleAPICredentialListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for apple-api-credential-list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
