// Code generated by go-swagger; DO NOT EDIT.

package generic_project_file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGenericProjectFileConfirmParams creates a new GenericProjectFileConfirmParams object
// with the default values initialized.
func NewGenericProjectFileConfirmParams() *GenericProjectFileConfirmParams {
	var ()
	return &GenericProjectFileConfirmParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGenericProjectFileConfirmParamsWithTimeout creates a new GenericProjectFileConfirmParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGenericProjectFileConfirmParamsWithTimeout(timeout time.Duration) *GenericProjectFileConfirmParams {
	var ()
	return &GenericProjectFileConfirmParams{

		timeout: timeout,
	}
}

// NewGenericProjectFileConfirmParamsWithContext creates a new GenericProjectFileConfirmParams object
// with the default values initialized, and the ability to set a context for a request
func NewGenericProjectFileConfirmParamsWithContext(ctx context.Context) *GenericProjectFileConfirmParams {
	var ()
	return &GenericProjectFileConfirmParams{

		Context: ctx,
	}
}

// NewGenericProjectFileConfirmParamsWithHTTPClient creates a new GenericProjectFileConfirmParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGenericProjectFileConfirmParamsWithHTTPClient(client *http.Client) *GenericProjectFileConfirmParams {
	var ()
	return &GenericProjectFileConfirmParams{
		HTTPClient: client,
	}
}

/*GenericProjectFileConfirmParams contains all the parameters to send to the API endpoint
for the generic project file confirm operation typically these are written to a http.Request
*/
type GenericProjectFileConfirmParams struct {

	/*AppSlug
	  App slug

	*/
	AppSlug string
	/*GenericProjectFileSlug
	  Generic project file slug

	*/
	GenericProjectFileSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the generic project file confirm params
func (o *GenericProjectFileConfirmParams) WithTimeout(timeout time.Duration) *GenericProjectFileConfirmParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generic project file confirm params
func (o *GenericProjectFileConfirmParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generic project file confirm params
func (o *GenericProjectFileConfirmParams) WithContext(ctx context.Context) *GenericProjectFileConfirmParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generic project file confirm params
func (o *GenericProjectFileConfirmParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generic project file confirm params
func (o *GenericProjectFileConfirmParams) WithHTTPClient(client *http.Client) *GenericProjectFileConfirmParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generic project file confirm params
func (o *GenericProjectFileConfirmParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppSlug adds the appSlug to the generic project file confirm params
func (o *GenericProjectFileConfirmParams) WithAppSlug(appSlug string) *GenericProjectFileConfirmParams {
	o.SetAppSlug(appSlug)
	return o
}

// SetAppSlug adds the appSlug to the generic project file confirm params
func (o *GenericProjectFileConfirmParams) SetAppSlug(appSlug string) {
	o.AppSlug = appSlug
}

// WithGenericProjectFileSlug adds the genericProjectFileSlug to the generic project file confirm params
func (o *GenericProjectFileConfirmParams) WithGenericProjectFileSlug(genericProjectFileSlug string) *GenericProjectFileConfirmParams {
	o.SetGenericProjectFileSlug(genericProjectFileSlug)
	return o
}

// SetGenericProjectFileSlug adds the genericProjectFileSlug to the generic project file confirm params
func (o *GenericProjectFileConfirmParams) SetGenericProjectFileSlug(genericProjectFileSlug string) {
	o.GenericProjectFileSlug = genericProjectFileSlug
}

// WriteToRequest writes these params to a swagger request
func (o *GenericProjectFileConfirmParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app-slug
	if err := r.SetPathParam("app-slug", o.AppSlug); err != nil {
		return err
	}

	// path param generic-project-file-slug
	if err := r.SetPathParam("generic-project-file-slug", o.GenericProjectFileSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
