// Code generated by go-swagger; DO NOT EDIT.

package webhook_delivery_item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewWebhookDeliveryItemShowParams creates a new WebhookDeliveryItemShowParams object
// with the default values initialized.
func NewWebhookDeliveryItemShowParams() *WebhookDeliveryItemShowParams {
	var ()
	return &WebhookDeliveryItemShowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWebhookDeliveryItemShowParamsWithTimeout creates a new WebhookDeliveryItemShowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWebhookDeliveryItemShowParamsWithTimeout(timeout time.Duration) *WebhookDeliveryItemShowParams {
	var ()
	return &WebhookDeliveryItemShowParams{

		timeout: timeout,
	}
}

// NewWebhookDeliveryItemShowParamsWithContext creates a new WebhookDeliveryItemShowParams object
// with the default values initialized, and the ability to set a context for a request
func NewWebhookDeliveryItemShowParamsWithContext(ctx context.Context) *WebhookDeliveryItemShowParams {
	var ()
	return &WebhookDeliveryItemShowParams{

		Context: ctx,
	}
}

// NewWebhookDeliveryItemShowParamsWithHTTPClient creates a new WebhookDeliveryItemShowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewWebhookDeliveryItemShowParamsWithHTTPClient(client *http.Client) *WebhookDeliveryItemShowParams {
	var ()
	return &WebhookDeliveryItemShowParams{
		HTTPClient: client,
	}
}

/*WebhookDeliveryItemShowParams contains all the parameters to send to the API endpoint
for the webhook delivery item show operation typically these are written to a http.Request
*/
type WebhookDeliveryItemShowParams struct {

	/*AppSlug
	  App slug

	*/
	AppSlug string
	/*AppWebhookSlug
	  App webhook slug

	*/
	AppWebhookSlug string
	/*WebhookDeliveryItemSlug
	  Webhook delivery item slug

	*/
	WebhookDeliveryItemSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) WithTimeout(timeout time.Duration) *WebhookDeliveryItemShowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) WithContext(ctx context.Context) *WebhookDeliveryItemShowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) WithHTTPClient(client *http.Client) *WebhookDeliveryItemShowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppSlug adds the appSlug to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) WithAppSlug(appSlug string) *WebhookDeliveryItemShowParams {
	o.SetAppSlug(appSlug)
	return o
}

// SetAppSlug adds the appSlug to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) SetAppSlug(appSlug string) {
	o.AppSlug = appSlug
}

// WithAppWebhookSlug adds the appWebhookSlug to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) WithAppWebhookSlug(appWebhookSlug string) *WebhookDeliveryItemShowParams {
	o.SetAppWebhookSlug(appWebhookSlug)
	return o
}

// SetAppWebhookSlug adds the appWebhookSlug to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) SetAppWebhookSlug(appWebhookSlug string) {
	o.AppWebhookSlug = appWebhookSlug
}

// WithWebhookDeliveryItemSlug adds the webhookDeliveryItemSlug to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) WithWebhookDeliveryItemSlug(webhookDeliveryItemSlug string) *WebhookDeliveryItemShowParams {
	o.SetWebhookDeliveryItemSlug(webhookDeliveryItemSlug)
	return o
}

// SetWebhookDeliveryItemSlug adds the webhookDeliveryItemSlug to the webhook delivery item show params
func (o *WebhookDeliveryItemShowParams) SetWebhookDeliveryItemSlug(webhookDeliveryItemSlug string) {
	o.WebhookDeliveryItemSlug = webhookDeliveryItemSlug
}

// WriteToRequest writes these params to a swagger request
func (o *WebhookDeliveryItemShowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app-slug
	if err := r.SetPathParam("app-slug", o.AppSlug); err != nil {
		return err
	}

	// path param app-webhook-slug
	if err := r.SetPathParam("app-webhook-slug", o.AppWebhookSlug); err != nil {
		return err
	}

	// path param webhook-delivery-item-slug
	if err := r.SetPathParam("webhook-delivery-item-slug", o.WebhookDeliveryItemSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
