// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewAppConfigDatastoreShowParams creates a new AppConfigDatastoreShowParams object
// with the default values initialized.
func NewAppConfigDatastoreShowParams() *AppConfigDatastoreShowParams {
	var ()
	return &AppConfigDatastoreShowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAppConfigDatastoreShowParamsWithTimeout creates a new AppConfigDatastoreShowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAppConfigDatastoreShowParamsWithTimeout(timeout time.Duration) *AppConfigDatastoreShowParams {
	var ()
	return &AppConfigDatastoreShowParams{

		timeout: timeout,
	}
}

// NewAppConfigDatastoreShowParamsWithContext creates a new AppConfigDatastoreShowParams object
// with the default values initialized, and the ability to set a context for a request
func NewAppConfigDatastoreShowParamsWithContext(ctx context.Context) *AppConfigDatastoreShowParams {
	var ()
	return &AppConfigDatastoreShowParams{

		Context: ctx,
	}
}

// NewAppConfigDatastoreShowParamsWithHTTPClient creates a new AppConfigDatastoreShowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAppConfigDatastoreShowParamsWithHTTPClient(client *http.Client) *AppConfigDatastoreShowParams {
	var ()
	return &AppConfigDatastoreShowParams{
		HTTPClient: client,
	}
}

/*AppConfigDatastoreShowParams contains all the parameters to send to the API endpoint
for the app config datastore show operation typically these are written to a http.Request
*/
type AppConfigDatastoreShowParams struct {

	/*AppSlug
	  App slug

	*/
	AppSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the app config datastore show params
func (o *AppConfigDatastoreShowParams) WithTimeout(timeout time.Duration) *AppConfigDatastoreShowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the app config datastore show params
func (o *AppConfigDatastoreShowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the app config datastore show params
func (o *AppConfigDatastoreShowParams) WithContext(ctx context.Context) *AppConfigDatastoreShowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the app config datastore show params
func (o *AppConfigDatastoreShowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the app config datastore show params
func (o *AppConfigDatastoreShowParams) WithHTTPClient(client *http.Client) *AppConfigDatastoreShowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the app config datastore show params
func (o *AppConfigDatastoreShowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppSlug adds the appSlug to the app config datastore show params
func (o *AppConfigDatastoreShowParams) WithAppSlug(appSlug string) *AppConfigDatastoreShowParams {
	o.SetAppSlug(appSlug)
	return o
}

// SetAppSlug adds the appSlug to the app config datastore show params
func (o *AppConfigDatastoreShowParams) SetAppSlug(appSlug string) {
	o.AppSlug = appSlug
}

// WriteToRequest writes these params to a swagger request
func (o *AppConfigDatastoreShowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app-slug
	if err := r.SetPathParam("app-slug", o.AppSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
