// Code generated by go-swagger; DO NOT EDIT.

package build_request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new build request API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for build request API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	BuildRequestList(params *BuildRequestListParams, authInfo runtime.ClientAuthInfoWriter) (*BuildRequestListOK, error)

	BuildRequestUpdate(params *BuildRequestUpdateParams, authInfo runtime.ClientAuthInfoWriter) (*BuildRequestUpdateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  BuildRequestList lists the open build requests for an app

  List the existing open build requests of a specified Bitrise app
*/
func (a *Client) BuildRequestList(params *BuildRequestListParams, authInfo runtime.ClientAuthInfoWriter) (*BuildRequestListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBuildRequestListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "build-request-list",
		Method:             "GET",
		PathPattern:        "/apps/{app-slug}/build-requests",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &BuildRequestListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*BuildRequestListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for build-request-list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  BuildRequestUpdate updates a build request

  Update a specific build request of a specific app
*/
func (a *Client) BuildRequestUpdate(params *BuildRequestUpdateParams, authInfo runtime.ClientAuthInfoWriter) (*BuildRequestUpdateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBuildRequestUpdateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "build-request-update",
		Method:             "PATCH",
		PathPattern:        "/apps/{app-slug}/build-requests/{build-request-slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &BuildRequestUpdateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*BuildRequestUpdateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for build-request-update: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
