// Code generated by go-swagger; DO NOT EDIT.

package build_request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new build request API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for build request API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
BuildRequestList lists the open build requests for an app

List the existing open build requests of a specified Bitrise app
*/
func (a *Client) BuildRequestList(params *BuildRequestListParams, authInfo runtime.ClientAuthInfoWriter) (*BuildRequestListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBuildRequestListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "build-request-list",
		Method:             "GET",
		PathPattern:        "/apps/{app-slug}/build-requests",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &BuildRequestListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*BuildRequestListOK), nil

}

/*
BuildRequestUpdate updates a build request

Update a specific build request of a specific app
*/
func (a *Client) BuildRequestUpdate(params *BuildRequestUpdateParams, authInfo runtime.ClientAuthInfoWriter) (*BuildRequestUpdateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBuildRequestUpdateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "build-request-update",
		Method:             "PATCH",
		PathPattern:        "/apps/{app-slug}/build-requests/{build-request-slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &BuildRequestUpdateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*BuildRequestUpdateOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
