// Code generated by go-swagger; DO NOT EDIT.

package test_devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTestDeviceListParams creates a new TestDeviceListParams object
// with the default values initialized.
func NewTestDeviceListParams() *TestDeviceListParams {
	var ()
	return &TestDeviceListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTestDeviceListParamsWithTimeout creates a new TestDeviceListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTestDeviceListParamsWithTimeout(timeout time.Duration) *TestDeviceListParams {
	var ()
	return &TestDeviceListParams{

		timeout: timeout,
	}
}

// NewTestDeviceListParamsWithContext creates a new TestDeviceListParams object
// with the default values initialized, and the ability to set a context for a request
func NewTestDeviceListParamsWithContext(ctx context.Context) *TestDeviceListParams {
	var ()
	return &TestDeviceListParams{

		Context: ctx,
	}
}

// NewTestDeviceListParamsWithHTTPClient creates a new TestDeviceListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTestDeviceListParamsWithHTTPClient(client *http.Client) *TestDeviceListParams {
	var ()
	return &TestDeviceListParams{
		HTTPClient: client,
	}
}

/*TestDeviceListParams contains all the parameters to send to the API endpoint
for the test device list operation typically these are written to a http.Request
*/
type TestDeviceListParams struct {

	/*AppSlug
	  App slug

	*/
	AppSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the test device list params
func (o *TestDeviceListParams) WithTimeout(timeout time.Duration) *TestDeviceListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the test device list params
func (o *TestDeviceListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the test device list params
func (o *TestDeviceListParams) WithContext(ctx context.Context) *TestDeviceListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the test device list params
func (o *TestDeviceListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the test device list params
func (o *TestDeviceListParams) WithHTTPClient(client *http.Client) *TestDeviceListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the test device list params
func (o *TestDeviceListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppSlug adds the appSlug to the test device list params
func (o *TestDeviceListParams) WithAppSlug(appSlug string) *TestDeviceListParams {
	o.SetAppSlug(appSlug)
	return o
}

// SetAppSlug adds the appSlug to the test device list params
func (o *TestDeviceListParams) SetAppSlug(appSlug string) {
	o.AppSlug = appSlug
}

// WriteToRequest writes these params to a swagger request
func (o *TestDeviceListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app-slug
	if err := r.SetPathParam("app-slug", o.AppSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
