// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V0AppWebhookResponseItemModel v0 app webhook response item model
// swagger:model v0.AppWebhookResponseItemModel
type V0AppWebhookResponseItemModel struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// events
	Events string `json:"events,omitempty"`

	// headers
	Headers string `json:"headers,omitempty"`

	// slug
	Slug string `json:"slug,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this v0 app webhook response item model
func (m *V0AppWebhookResponseItemModel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0AppWebhookResponseItemModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0AppWebhookResponseItemModel) UnmarshalBinary(b []byte) error {
	var res V0AppWebhookResponseItemModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
