// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V0AppWebhookUpdateParams v0 app webhook update params
// swagger:model v0.AppWebhookUpdateParams
type V0AppWebhookUpdateParams struct {

	// events
	Events string `json:"events,omitempty"`

	// headers
	Headers string `json:"headers,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this v0 app webhook update params
func (m *V0AppWebhookUpdateParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0AppWebhookUpdateParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0AppWebhookUpdateParams) UnmarshalBinary(b []byte) error {
	var res V0AppWebhookUpdateParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
