// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// V0AppConfigRespModel v0 app config resp model
// swagger:model v0.AppConfigRespModel
type V0AppConfigRespModel map[string]string

// Validate validates this v0 app config resp model
func (m V0AppConfigRespModel) Validate(formats strfmt.Registry) error {
	return nil
}
