// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V0AppFinishParams v0 app finish params
// swagger:model v0.AppFinishParams
type V0AppFinishParams struct {

	// config
	Config string `json:"config,omitempty"`

	// envs
	Envs interface{} `json:"envs,omitempty"`

	// mode
	Mode string `json:"mode,omitempty"`

	// organization slug
	OrganizationSlug string `json:"organization_slug,omitempty"`

	// project type
	ProjectType string `json:"project_type,omitempty"`

	// stack id
	StackID string `json:"stack_id,omitempty"`
}

// Validate validates this v0 app finish params
func (m *V0AppFinishParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0AppFinishParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0AppFinishParams) UnmarshalBinary(b []byte) error {
	var res V0AppFinishParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
