// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V0AppWebhookCreateParams v0 app webhook create params
// swagger:model v0.AppWebhookCreateParams
type V0AppWebhookCreateParams struct {

	// events
	Events string `json:"events,omitempty"`

	// headers
	Headers string `json:"headers,omitempty"`

	// secret
	Secret string `json:"secret,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this v0 app webhook create params
func (m *V0AppWebhookCreateParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0AppWebhookCreateParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0AppWebhookCreateParams) UnmarshalBinary(b []byte) error {
	var res V0AppWebhookCreateParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
