// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V0AvatarCandidateCreateParams v0 avatar candidate create params
// swagger:model v0.AvatarCandidateCreateParams
type V0AvatarCandidateCreateParams struct {

	// filename
	Filename string `json:"filename,omitempty"`

	// filesize
	Filesize int64 `json:"filesize,omitempty"`
}

// Validate validates this v0 avatar candidate create params
func (m *V0AvatarCandidateCreateParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0AvatarCandidateCreateParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0AvatarCandidateCreateParams) UnmarshalBinary(b []byte) error {
	var res V0AvatarCandidateCreateParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
