// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V0AppConfigRespModel v0 app config resp model
// swagger:model v0.AppConfigRespModel
type V0AppConfigRespModel interface{}
