// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V0ProjectFileStorageUploadParams v0 project file storage upload params
// swagger:model v0.ProjectFileStorageUploadParams
type V0ProjectFileStorageUploadParams struct {

	// upload file name
	UploadFileName string `json:"upload_file_name,omitempty"`

	// upload file size
	UploadFileSize int64 `json:"upload_file_size,omitempty"`

	// user env key
	UserEnvKey string `json:"user_env_key,omitempty"`
}

// Validate validates this v0 project file storage upload params
func (m *V0ProjectFileStorageUploadParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0ProjectFileStorageUploadParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0ProjectFileStorageUploadParams) UnmarshalBinary(b []byte) error {
	var res V0ProjectFileStorageUploadParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
